removed a few things while also adding build system

diff --git a/compile b/compile
--- a/compile
+++ b/compile
@@ -7,11 +7,13 @@ case $1 in
 		;;
 
 	build)
-		cc -c -Iinclude src/pl32-memory.c src/pl32-shell.c src/pl32-file.c -g
-		ar rc libpl32.a *.o
-		cc -c -fPIC -Iinclude src/pl32-memory.c src/pl32-shell.c src/pl32-file.c -g
-		cc -shared *.o -o libpl32.so
-		cc --static -Iinclude pl32-test.c *.o -o pl32-test.out -g
+		if [ ! -f /usr/lib/libpl32.so ]; then
+			echo "Error: pl32lib is not installed"
+			exit 1
+		fi
+		cc -c -Iinclude src/file-io.c $FLAGS
+#		cc -c -Iinclude src/net-io.c $FLAGS
+#		cc -Iinclude src/main.c *.o $FLAGS
 		rm *.o
 		;;
 	install)
